`ifndef NR_LDPC_CONTROLLER_PROFILE_BG1_FIRST4_SV
`define NR_LDPC_CONTROLLER_PROFILE_BG1_FIRST4_SV

// Generated by scripts/generate_phase9_controller_profile.py.
// Sources: Category-A schedule/profile/QC-shift artifacts, Category-B evidence, and NR_1_1_384.txt.
package nr_ldpc_controller_profile_bg1_first4_pkg;
  localparam int PHASE9_PROGRAM_LENGTH = 71;
  localparam int PHASE9_ACC_ISSUES = 40;
  localparam int PHASE9_REC_ISSUES = 40;
  localparam int PHASE9_ACC_EDGES = 76;
  localparam int PHASE9_REC_EDGES = 76;
  localparam int PHASE9_ACTIVE_COLUMNS = 26;
  localparam int PHASE9_LAYER_DEGREE = 19;
  localparam int PHASE9_SYNDROME_COMPLETION_CYCLE = 72;
  localparam int PHASE9_SYNDROME_TAIL = 1;

  function automatic logic [71:0] phase9_program_word(input logic [8:0] pc);
    begin
      phase9_program_word = 72'd0;
      case (pc)
        0: phase9_program_word = 72'd16399;
        1: phase9_program_word = 72'd777247;
        2: phase9_program_word = 72'd1098767;
        3: phase9_program_word = 72'd1638943;
        4: phase9_program_word = 72'd2181135;
        5: phase9_program_word = 72'd2788895;
        6: phase9_program_word = 72'd3263503;
        7: phase9_program_word = 72'd4345871;
        8: phase9_program_word = 72'd5428239;
        9: phase9_program_word = 72'd6510607;
        10: phase9_program_word = 72'd7592975;
        11: phase9_program_word = 72'd8675343;
        12: phase9_program_word = 72'd9446411;
        13: phase9_program_word = 72'd9970715;
        14: phase9_program_word = 72'd0;
        15: phase9_program_word = 72'd38121916345320734720;
        16: phase9_program_word = 72'd77544386789740904448;
        17: phase9_program_word = 72'd116892477471565283328;
        18: phase9_program_word = 72'd155645530053180703775;
        19: phase9_program_word = 72'd20902473539943813151;
        20: phase9_program_word = 72'd77470007027145113600;
        21: phase9_program_word = 72'd116818097709096058911;
        22: phase9_program_word = 72'd138872365822228104215;
        23: phase9_program_word = 72'd38642574684301396511;
        24: phase9_program_word = 72'd4107916936386646039;
        25: phase9_program_word = 72'd7018015;
        26: phase9_program_word = 72'd276586527;
        27: phase9_program_word = 72'd806641175;
        28: phase9_program_word = 72'd0;
        29: phase9_program_word = 72'd38099821659160576000;
        30: phase9_program_word = 72'd77358368114018877440;
        31: phase9_program_word = 72'd116636723370363191296;
        32: phase9_program_word = 72'd155975595746700296192;
        33: phase9_program_word = 72'd38673538030441070592;
        34: phase9_program_word = 72'd60207570019157185047;
        35: phase9_program_word = 72'd116927346285700286999;
        36: phase9_program_word = 72'd8755632849751654423;
        37: phase9_program_word = 72'd38453143123735463447;
        38: phase9_program_word = 72'd77805878142720317447;
        39: phase9_program_word = 72'd1886691351;
        40: phase9_program_word = 72'd554323975;
        41: phase9_program_word = 72'd1125933063;
        42: phase9_program_word = 72'd6527511;
        43: phase9_program_word = 72'd9442835;
        44: phase9_program_word = 72'd9963011;
        45: phase9_program_word = 72'd0;
        46: phase9_program_word = 72'd38050985200945463296;
        47: phase9_program_word = 72'd77403649851141390336;
        48: phase9_program_word = 72'd116662372227860135936;
        49: phase9_program_word = 72'd156016268331079172096;
        50: phase9_program_word = 72'd591540459101896048640;
        51: phase9_program_word = 72'd592896816647618707463;
        52: phase9_program_word = 72'd350936704542674897927;
        53: phase9_program_word = 72'd595432730264230089735;
        54: phase9_program_word = 72'd886028164723915704327;
        55: phase9_program_word = 72'd295796811859515644423;
        56: phase9_program_word = 72'd1082901511;
        57: phase9_program_word = 72'd0;
        58: phase9_program_word = 72'd0;
        59: phase9_program_word = 72'd885490159390252072960;
        60: phase9_program_word = 72'd885571505658521452544;
        61: phase9_program_word = 72'd885644548414977867776;
        62: phase9_program_word = 72'd885697043498134405120;
        63: phase9_program_word = 72'd885773745429288058880;
        64: phase9_program_word = 72'd885848125191883849728;
        65: phase9_program_word = 72'd885924827123037503488;
        66: phase9_program_word = 72'd886000367969912225792;
        67: phase9_program_word = 72'd886073164435764019200;
        68: phase9_program_word = 72'd295832558081987837952;
        69: phase9_program_word = 72'd0;
        70: phase9_program_word = 72'd0;
        default: begin end
      endcase
    end
  endfunction

  function automatic logic phase9_active_layer(input logic [5:0] layer_id);
    begin
      case (layer_id)
        6'd0, 6'd1, 6'd2, 6'd3: phase9_active_layer = 1'b1;
        default: phase9_active_layer = 1'b0;
      endcase
    end
  endfunction

  function automatic logic [5:0] phase9_layer_position(input logic [5:0] layer_id);
    begin
      phase9_layer_position = 6'd63;
      case (layer_id)
        0: phase9_layer_position = 6'd3;
        1: phase9_layer_position = 6'd0;
        2: phase9_layer_position = 6'd2;
        3: phase9_layer_position = 6'd1;
        default: begin end
      endcase
    end
  endfunction

  function automatic logic [5:0] phase9_layer_order(input logic [1:0] position);
    begin
      phase9_layer_order = 6'd63;
      case (position)
        0: phase9_layer_order = 6'd1;
        1: phase9_layer_order = 6'd3;
        2: phase9_layer_order = 6'd2;
        3: phase9_layer_order = 6'd0;
        default: begin end
      endcase
    end
  endfunction

  function automatic logic [5:0] phase9_layer_degree(input logic [5:0] layer_id);
    begin
      phase9_layer_degree = 6'd0;
      case (layer_id)
        0: phase9_layer_degree = 6'd19;
        1: phase9_layer_degree = 6'd19;
        2: phase9_layer_degree = 6'd19;
        3: phase9_layer_degree = 6'd19;
        default: begin end
      endcase
    end
  endfunction

  function automatic logic [6:0] phase9_edge_base_column(input logic [5:0] layer_id, input logic [4:0] local_edge_id);
    begin
      phase9_edge_base_column = 7'd127;
      case ({layer_id, local_edge_id})
        0: phase9_edge_base_column = 7'd0;
        1: phase9_edge_base_column = 7'd1;
        2: phase9_edge_base_column = 7'd2;
        3: phase9_edge_base_column = 7'd3;
        4: phase9_edge_base_column = 7'd5;
        5: phase9_edge_base_column = 7'd6;
        6: phase9_edge_base_column = 7'd9;
        7: phase9_edge_base_column = 7'd10;
        8: phase9_edge_base_column = 7'd11;
        9: phase9_edge_base_column = 7'd12;
        10: phase9_edge_base_column = 7'd13;
        11: phase9_edge_base_column = 7'd15;
        12: phase9_edge_base_column = 7'd16;
        13: phase9_edge_base_column = 7'd18;
        14: phase9_edge_base_column = 7'd19;
        15: phase9_edge_base_column = 7'd20;
        16: phase9_edge_base_column = 7'd21;
        17: phase9_edge_base_column = 7'd22;
        18: phase9_edge_base_column = 7'd23;
        32: phase9_edge_base_column = 7'd0;
        33: phase9_edge_base_column = 7'd2;
        34: phase9_edge_base_column = 7'd3;
        35: phase9_edge_base_column = 7'd4;
        36: phase9_edge_base_column = 7'd5;
        37: phase9_edge_base_column = 7'd7;
        38: phase9_edge_base_column = 7'd8;
        39: phase9_edge_base_column = 7'd9;
        40: phase9_edge_base_column = 7'd11;
        41: phase9_edge_base_column = 7'd12;
        42: phase9_edge_base_column = 7'd14;
        43: phase9_edge_base_column = 7'd15;
        44: phase9_edge_base_column = 7'd16;
        45: phase9_edge_base_column = 7'd17;
        46: phase9_edge_base_column = 7'd19;
        47: phase9_edge_base_column = 7'd21;
        48: phase9_edge_base_column = 7'd22;
        49: phase9_edge_base_column = 7'd23;
        50: phase9_edge_base_column = 7'd24;
        64: phase9_edge_base_column = 7'd0;
        65: phase9_edge_base_column = 7'd1;
        66: phase9_edge_base_column = 7'd2;
        67: phase9_edge_base_column = 7'd4;
        68: phase9_edge_base_column = 7'd5;
        69: phase9_edge_base_column = 7'd6;
        70: phase9_edge_base_column = 7'd7;
        71: phase9_edge_base_column = 7'd8;
        72: phase9_edge_base_column = 7'd9;
        73: phase9_edge_base_column = 7'd10;
        74: phase9_edge_base_column = 7'd13;
        75: phase9_edge_base_column = 7'd14;
        76: phase9_edge_base_column = 7'd15;
        77: phase9_edge_base_column = 7'd17;
        78: phase9_edge_base_column = 7'd18;
        79: phase9_edge_base_column = 7'd19;
        80: phase9_edge_base_column = 7'd20;
        81: phase9_edge_base_column = 7'd24;
        82: phase9_edge_base_column = 7'd25;
        96: phase9_edge_base_column = 7'd0;
        97: phase9_edge_base_column = 7'd1;
        98: phase9_edge_base_column = 7'd3;
        99: phase9_edge_base_column = 7'd4;
        100: phase9_edge_base_column = 7'd6;
        101: phase9_edge_base_column = 7'd7;
        102: phase9_edge_base_column = 7'd8;
        103: phase9_edge_base_column = 7'd10;
        104: phase9_edge_base_column = 7'd11;
        105: phase9_edge_base_column = 7'd12;
        106: phase9_edge_base_column = 7'd13;
        107: phase9_edge_base_column = 7'd14;
        108: phase9_edge_base_column = 7'd16;
        109: phase9_edge_base_column = 7'd17;
        110: phase9_edge_base_column = 7'd18;
        111: phase9_edge_base_column = 7'd20;
        112: phase9_edge_base_column = 7'd21;
        113: phase9_edge_base_column = 7'd22;
        114: phase9_edge_base_column = 7'd25;
        default: begin end
      endcase
    end
  endfunction

  function automatic logic [8:0] phase9_edge_shift(input logic [5:0] layer_id, input logic [4:0] local_edge_id);
    begin
      phase9_edge_shift = 9'd0;
      case ({layer_id, local_edge_id})
        0: phase9_edge_shift = 9'd307;
        1: phase9_edge_shift = 9'd19;
        2: phase9_edge_shift = 9'd50;
        3: phase9_edge_shift = 9'd369;
        4: phase9_edge_shift = 9'd181;
        5: phase9_edge_shift = 9'd216;
        6: phase9_edge_shift = 9'd317;
        7: phase9_edge_shift = 9'd288;
        8: phase9_edge_shift = 9'd109;
        9: phase9_edge_shift = 9'd17;
        10: phase9_edge_shift = 9'd357;
        11: phase9_edge_shift = 9'd215;
        12: phase9_edge_shift = 9'd106;
        13: phase9_edge_shift = 9'd242;
        14: phase9_edge_shift = 9'd180;
        15: phase9_edge_shift = 9'd330;
        16: phase9_edge_shift = 9'd346;
        17: phase9_edge_shift = 9'd1;
        18: phase9_edge_shift = 9'd0;
        32: phase9_edge_shift = 9'd76;
        33: phase9_edge_shift = 9'd76;
        34: phase9_edge_shift = 9'd73;
        35: phase9_edge_shift = 9'd288;
        36: phase9_edge_shift = 9'd144;
        37: phase9_edge_shift = 9'd331;
        38: phase9_edge_shift = 9'd331;
        39: phase9_edge_shift = 9'd178;
        40: phase9_edge_shift = 9'd295;
        41: phase9_edge_shift = 9'd342;
        42: phase9_edge_shift = 9'd217;
        43: phase9_edge_shift = 9'd99;
        44: phase9_edge_shift = 9'd354;
        45: phase9_edge_shift = 9'd114;
        46: phase9_edge_shift = 9'd331;
        47: phase9_edge_shift = 9'd112;
        48: phase9_edge_shift = 9'd0;
        49: phase9_edge_shift = 9'd0;
        50: phase9_edge_shift = 9'd0;
        64: phase9_edge_shift = 9'd205;
        65: phase9_edge_shift = 9'd250;
        66: phase9_edge_shift = 9'd328;
        67: phase9_edge_shift = 9'd332;
        68: phase9_edge_shift = 9'd256;
        69: phase9_edge_shift = 9'd161;
        70: phase9_edge_shift = 9'd267;
        71: phase9_edge_shift = 9'd160;
        72: phase9_edge_shift = 9'd63;
        73: phase9_edge_shift = 9'd129;
        74: phase9_edge_shift = 9'd200;
        75: phase9_edge_shift = 9'd88;
        76: phase9_edge_shift = 9'd53;
        77: phase9_edge_shift = 9'd131;
        78: phase9_edge_shift = 9'd240;
        79: phase9_edge_shift = 9'd205;
        80: phase9_edge_shift = 9'd13;
        81: phase9_edge_shift = 9'd0;
        82: phase9_edge_shift = 9'd0;
        96: phase9_edge_shift = 9'd276;
        97: phase9_edge_shift = 9'd87;
        98: phase9_edge_shift = 9'd0;
        99: phase9_edge_shift = 9'd275;
        100: phase9_edge_shift = 9'd199;
        101: phase9_edge_shift = 9'd153;
        102: phase9_edge_shift = 9'd56;
        103: phase9_edge_shift = 9'd132;
        104: phase9_edge_shift = 9'd305;
        105: phase9_edge_shift = 9'd231;
        106: phase9_edge_shift = 9'd341;
        107: phase9_edge_shift = 9'd212;
        108: phase9_edge_shift = 9'd304;
        109: phase9_edge_shift = 9'd300;
        110: phase9_edge_shift = 9'd271;
        111: phase9_edge_shift = 9'd39;
        112: phase9_edge_shift = 9'd357;
        113: phase9_edge_shift = 9'd1;
        114: phase9_edge_shift = 9'd0;
        default: begin end
      endcase
    end
  endfunction

  function automatic logic phase9_edge_valid(input logic [5:0] layer_id, input logic [4:0] local_edge_id);
    begin
      phase9_edge_valid = 1'b0;
      case ({layer_id, local_edge_id})
        0: phase9_edge_valid = 1'b1;
        1: phase9_edge_valid = 1'b1;
        2: phase9_edge_valid = 1'b1;
        3: phase9_edge_valid = 1'b1;
        4: phase9_edge_valid = 1'b1;
        5: phase9_edge_valid = 1'b1;
        6: phase9_edge_valid = 1'b1;
        7: phase9_edge_valid = 1'b1;
        8: phase9_edge_valid = 1'b1;
        9: phase9_edge_valid = 1'b1;
        10: phase9_edge_valid = 1'b1;
        11: phase9_edge_valid = 1'b1;
        12: phase9_edge_valid = 1'b1;
        13: phase9_edge_valid = 1'b1;
        14: phase9_edge_valid = 1'b1;
        15: phase9_edge_valid = 1'b1;
        16: phase9_edge_valid = 1'b1;
        17: phase9_edge_valid = 1'b1;
        18: phase9_edge_valid = 1'b1;
        32: phase9_edge_valid = 1'b1;
        33: phase9_edge_valid = 1'b1;
        34: phase9_edge_valid = 1'b1;
        35: phase9_edge_valid = 1'b1;
        36: phase9_edge_valid = 1'b1;
        37: phase9_edge_valid = 1'b1;
        38: phase9_edge_valid = 1'b1;
        39: phase9_edge_valid = 1'b1;
        40: phase9_edge_valid = 1'b1;
        41: phase9_edge_valid = 1'b1;
        42: phase9_edge_valid = 1'b1;
        43: phase9_edge_valid = 1'b1;
        44: phase9_edge_valid = 1'b1;
        45: phase9_edge_valid = 1'b1;
        46: phase9_edge_valid = 1'b1;
        47: phase9_edge_valid = 1'b1;
        48: phase9_edge_valid = 1'b1;
        49: phase9_edge_valid = 1'b1;
        50: phase9_edge_valid = 1'b1;
        64: phase9_edge_valid = 1'b1;
        65: phase9_edge_valid = 1'b1;
        66: phase9_edge_valid = 1'b1;
        67: phase9_edge_valid = 1'b1;
        68: phase9_edge_valid = 1'b1;
        69: phase9_edge_valid = 1'b1;
        70: phase9_edge_valid = 1'b1;
        71: phase9_edge_valid = 1'b1;
        72: phase9_edge_valid = 1'b1;
        73: phase9_edge_valid = 1'b1;
        74: phase9_edge_valid = 1'b1;
        75: phase9_edge_valid = 1'b1;
        76: phase9_edge_valid = 1'b1;
        77: phase9_edge_valid = 1'b1;
        78: phase9_edge_valid = 1'b1;
        79: phase9_edge_valid = 1'b1;
        80: phase9_edge_valid = 1'b1;
        81: phase9_edge_valid = 1'b1;
        82: phase9_edge_valid = 1'b1;
        96: phase9_edge_valid = 1'b1;
        97: phase9_edge_valid = 1'b1;
        98: phase9_edge_valid = 1'b1;
        99: phase9_edge_valid = 1'b1;
        100: phase9_edge_valid = 1'b1;
        101: phase9_edge_valid = 1'b1;
        102: phase9_edge_valid = 1'b1;
        103: phase9_edge_valid = 1'b1;
        104: phase9_edge_valid = 1'b1;
        105: phase9_edge_valid = 1'b1;
        106: phase9_edge_valid = 1'b1;
        107: phase9_edge_valid = 1'b1;
        108: phase9_edge_valid = 1'b1;
        109: phase9_edge_valid = 1'b1;
        110: phase9_edge_valid = 1'b1;
        111: phase9_edge_valid = 1'b1;
        112: phase9_edge_valid = 1'b1;
        113: phase9_edge_valid = 1'b1;
        114: phase9_edge_valid = 1'b1;
        default: begin end
      endcase
    end
  endfunction
endpackage

`endif
