`ifndef NR_LDPC_SYNDROME_PROFILE_BG1_FIRST4_SV
`define NR_LDPC_SYNDROME_PROFILE_BG1_FIRST4_SV

// Generated by scripts/generate_phase8_syndrome_profile.py.
// Source: data/NR-LDPC-BG/NR_1_1_384.txt plus checked-in syndrome artifacts.
package nr_ldpc_syndrome_profile_bg1_first4_pkg;
  localparam int PHASE8_ACTIVE_ROWS = 4;
  localparam int PHASE8_ACTIVE_COLUMNS = 26;
  localparam int PHASE8_WORK_ITEMS = 76;
  localparam int PHASE8_FIRST_FINAL_CYCLE = 53;
  localparam int PHASE8_LAST_FINAL_CYCLE = 71;
  localparam int PHASE8_EXPECTED_COMPLETION_CYCLE = 72;
  localparam int PHASE8_EXPECTED_TAIL = 1;
  localparam int PHASE8_EXPECTED_MAX_BACKLOG = 7;
  localparam int PHASE8_EXPECTED_MAX_QUEUE_OCCUPANCY = 2;

  function automatic logic phase8_active_column(input logic [6:0] column);
    begin
      phase8_active_column = (column < 7'd26);
    end
  endfunction

  function automatic logic [4:0] phase8_column_index(input logic [6:0] column);
    begin
      phase8_column_index = column[4:0];
    end
  endfunction

  function automatic logic [4:0] phase8_column_work_count(input logic [6:0] column);
    begin
      phase8_column_work_count = 5'd0;
      case (column)
        7'd0: phase8_column_work_count = 5'd4;
        7'd1: phase8_column_work_count = 5'd3;
        7'd2: phase8_column_work_count = 5'd3;
        7'd3: phase8_column_work_count = 5'd3;
        7'd4: phase8_column_work_count = 5'd3;
        7'd5: phase8_column_work_count = 5'd3;
        7'd6: phase8_column_work_count = 5'd3;
        7'd7: phase8_column_work_count = 5'd3;
        7'd8: phase8_column_work_count = 5'd3;
        7'd9: phase8_column_work_count = 5'd3;
        7'd10: phase8_column_work_count = 5'd3;
        7'd11: phase8_column_work_count = 5'd3;
        7'd12: phase8_column_work_count = 5'd3;
        7'd13: phase8_column_work_count = 5'd3;
        7'd14: phase8_column_work_count = 5'd3;
        7'd15: phase8_column_work_count = 5'd3;
        7'd16: phase8_column_work_count = 5'd3;
        7'd17: phase8_column_work_count = 5'd3;
        7'd18: phase8_column_work_count = 5'd3;
        7'd19: phase8_column_work_count = 5'd3;
        7'd20: phase8_column_work_count = 5'd3;
        7'd21: phase8_column_work_count = 5'd3;
        7'd22: phase8_column_work_count = 5'd3;
        7'd23: phase8_column_work_count = 5'd2;
        7'd24: phase8_column_work_count = 5'd2;
        7'd25: phase8_column_work_count = 5'd2;
        default: begin end
      endcase
    end
  endfunction

  function automatic logic [6:0] phase8_column_work_start(input logic [6:0] column);
    begin
      phase8_column_work_start = 7'd76;
      case (column)
        7'd0: phase8_column_work_start = 7'd0;
        7'd1: phase8_column_work_start = 7'd4;
        7'd2: phase8_column_work_start = 7'd7;
        7'd3: phase8_column_work_start = 7'd10;
        7'd4: phase8_column_work_start = 7'd13;
        7'd5: phase8_column_work_start = 7'd16;
        7'd6: phase8_column_work_start = 7'd19;
        7'd7: phase8_column_work_start = 7'd22;
        7'd8: phase8_column_work_start = 7'd25;
        7'd9: phase8_column_work_start = 7'd28;
        7'd10: phase8_column_work_start = 7'd31;
        7'd11: phase8_column_work_start = 7'd34;
        7'd12: phase8_column_work_start = 7'd37;
        7'd13: phase8_column_work_start = 7'd40;
        7'd14: phase8_column_work_start = 7'd43;
        7'd15: phase8_column_work_start = 7'd46;
        7'd16: phase8_column_work_start = 7'd49;
        7'd17: phase8_column_work_start = 7'd52;
        7'd18: phase8_column_work_start = 7'd55;
        7'd19: phase8_column_work_start = 7'd58;
        7'd20: phase8_column_work_start = 7'd61;
        7'd21: phase8_column_work_start = 7'd64;
        7'd22: phase8_column_work_start = 7'd67;
        7'd23: phase8_column_work_start = 7'd70;
        7'd24: phase8_column_work_start = 7'd72;
        7'd25: phase8_column_work_start = 7'd74;
        default: begin end
      endcase
    end
  endfunction

  function automatic logic [6:0] phase8_column_final_cycle(input logic [6:0] column);
    begin
      phase8_column_final_cycle = 7'd0;
      case (column)
        7'd0: phase8_column_final_cycle = 7'd65;
        7'd1: phase8_column_final_cycle = 7'd65;
        7'd2: phase8_column_final_cycle = 7'd70;
        7'd3: phase8_column_final_cycle = 7'd71;
        7'd4: phase8_column_final_cycle = 7'd57;
        7'd5: phase8_column_final_cycle = 7'd66;
        7'd6: phase8_column_final_cycle = 7'd66;
        7'd7: phase8_column_final_cycle = 7'd54;
        7'd8: phase8_column_final_cycle = 7'd57;
        7'd9: phase8_column_final_cycle = 7'd67;
        7'd10: phase8_column_final_cycle = 7'd67;
        7'd11: phase8_column_final_cycle = 7'd62;
        7'd12: phase8_column_final_cycle = 7'd62;
        7'd13: phase8_column_final_cycle = 7'd68;
        7'd14: phase8_column_final_cycle = 7'd58;
        7'd15: phase8_column_final_cycle = 7'd68;
        7'd16: phase8_column_final_cycle = 7'd64;
        7'd17: phase8_column_final_cycle = 7'd55;
        7'd18: phase8_column_final_cycle = 7'd69;
        7'd19: phase8_column_final_cycle = 7'd69;
        7'd20: phase8_column_final_cycle = 7'd70;
        7'd21: phase8_column_final_cycle = 7'd63;
        7'd22: phase8_column_final_cycle = 7'd63;
        7'd23: phase8_column_final_cycle = 7'd64;
        7'd24: phase8_column_final_cycle = 7'd53;
        7'd25: phase8_column_final_cycle = 7'd56;
        default: begin end
      endcase
    end
  endfunction

  function automatic logic [1:0] phase8_work_row(input logic [6:0] work_id);
    begin
      phase8_work_row = 2'd0;
      case (work_id)
        7'd0: phase8_work_row = 2'd0;
        7'd1: phase8_work_row = 2'd1;
        7'd2: phase8_work_row = 2'd2;
        7'd3: phase8_work_row = 2'd3;
        7'd4: phase8_work_row = 2'd0;
        7'd5: phase8_work_row = 2'd2;
        7'd6: phase8_work_row = 2'd3;
        7'd7: phase8_work_row = 2'd0;
        7'd8: phase8_work_row = 2'd1;
        7'd9: phase8_work_row = 2'd2;
        7'd10: phase8_work_row = 2'd0;
        7'd11: phase8_work_row = 2'd1;
        7'd12: phase8_work_row = 2'd3;
        7'd13: phase8_work_row = 2'd1;
        7'd14: phase8_work_row = 2'd2;
        7'd15: phase8_work_row = 2'd3;
        7'd16: phase8_work_row = 2'd0;
        7'd17: phase8_work_row = 2'd1;
        7'd18: phase8_work_row = 2'd2;
        7'd19: phase8_work_row = 2'd0;
        7'd20: phase8_work_row = 2'd2;
        7'd21: phase8_work_row = 2'd3;
        7'd22: phase8_work_row = 2'd1;
        7'd23: phase8_work_row = 2'd2;
        7'd24: phase8_work_row = 2'd3;
        7'd25: phase8_work_row = 2'd1;
        7'd26: phase8_work_row = 2'd2;
        7'd27: phase8_work_row = 2'd3;
        7'd28: phase8_work_row = 2'd0;
        7'd29: phase8_work_row = 2'd1;
        7'd30: phase8_work_row = 2'd2;
        7'd31: phase8_work_row = 2'd0;
        7'd32: phase8_work_row = 2'd2;
        7'd33: phase8_work_row = 2'd3;
        7'd34: phase8_work_row = 2'd0;
        7'd35: phase8_work_row = 2'd1;
        7'd36: phase8_work_row = 2'd3;
        7'd37: phase8_work_row = 2'd0;
        7'd38: phase8_work_row = 2'd1;
        7'd39: phase8_work_row = 2'd3;
        7'd40: phase8_work_row = 2'd0;
        7'd41: phase8_work_row = 2'd2;
        7'd42: phase8_work_row = 2'd3;
        7'd43: phase8_work_row = 2'd1;
        7'd44: phase8_work_row = 2'd2;
        7'd45: phase8_work_row = 2'd3;
        7'd46: phase8_work_row = 2'd0;
        7'd47: phase8_work_row = 2'd1;
        7'd48: phase8_work_row = 2'd2;
        7'd49: phase8_work_row = 2'd0;
        7'd50: phase8_work_row = 2'd1;
        7'd51: phase8_work_row = 2'd3;
        7'd52: phase8_work_row = 2'd1;
        7'd53: phase8_work_row = 2'd2;
        7'd54: phase8_work_row = 2'd3;
        7'd55: phase8_work_row = 2'd0;
        7'd56: phase8_work_row = 2'd2;
        7'd57: phase8_work_row = 2'd3;
        7'd58: phase8_work_row = 2'd0;
        7'd59: phase8_work_row = 2'd1;
        7'd60: phase8_work_row = 2'd2;
        7'd61: phase8_work_row = 2'd0;
        7'd62: phase8_work_row = 2'd2;
        7'd63: phase8_work_row = 2'd3;
        7'd64: phase8_work_row = 2'd0;
        7'd65: phase8_work_row = 2'd1;
        7'd66: phase8_work_row = 2'd3;
        7'd67: phase8_work_row = 2'd0;
        7'd68: phase8_work_row = 2'd1;
        7'd69: phase8_work_row = 2'd3;
        7'd70: phase8_work_row = 2'd0;
        7'd71: phase8_work_row = 2'd1;
        7'd72: phase8_work_row = 2'd1;
        7'd73: phase8_work_row = 2'd2;
        7'd74: phase8_work_row = 2'd2;
        7'd75: phase8_work_row = 2'd3;
        default: begin end
      endcase
    end
  endfunction

  function automatic logic [4:0] phase8_work_edge(input logic [6:0] work_id);
    begin
      phase8_work_edge = 5'd0;
      case (work_id)
        7'd0: phase8_work_edge = 5'd0;
        7'd1: phase8_work_edge = 5'd0;
        7'd2: phase8_work_edge = 5'd0;
        7'd3: phase8_work_edge = 5'd0;
        7'd4: phase8_work_edge = 5'd1;
        7'd5: phase8_work_edge = 5'd1;
        7'd6: phase8_work_edge = 5'd1;
        7'd7: phase8_work_edge = 5'd2;
        7'd8: phase8_work_edge = 5'd1;
        7'd9: phase8_work_edge = 5'd2;
        7'd10: phase8_work_edge = 5'd3;
        7'd11: phase8_work_edge = 5'd2;
        7'd12: phase8_work_edge = 5'd2;
        7'd13: phase8_work_edge = 5'd3;
        7'd14: phase8_work_edge = 5'd3;
        7'd15: phase8_work_edge = 5'd3;
        7'd16: phase8_work_edge = 5'd4;
        7'd17: phase8_work_edge = 5'd4;
        7'd18: phase8_work_edge = 5'd4;
        7'd19: phase8_work_edge = 5'd5;
        7'd20: phase8_work_edge = 5'd5;
        7'd21: phase8_work_edge = 5'd4;
        7'd22: phase8_work_edge = 5'd5;
        7'd23: phase8_work_edge = 5'd6;
        7'd24: phase8_work_edge = 5'd5;
        7'd25: phase8_work_edge = 5'd6;
        7'd26: phase8_work_edge = 5'd7;
        7'd27: phase8_work_edge = 5'd6;
        7'd28: phase8_work_edge = 5'd6;
        7'd29: phase8_work_edge = 5'd7;
        7'd30: phase8_work_edge = 5'd8;
        7'd31: phase8_work_edge = 5'd7;
        7'd32: phase8_work_edge = 5'd9;
        7'd33: phase8_work_edge = 5'd7;
        7'd34: phase8_work_edge = 5'd8;
        7'd35: phase8_work_edge = 5'd8;
        7'd36: phase8_work_edge = 5'd8;
        7'd37: phase8_work_edge = 5'd9;
        7'd38: phase8_work_edge = 5'd9;
        7'd39: phase8_work_edge = 5'd9;
        7'd40: phase8_work_edge = 5'd10;
        7'd41: phase8_work_edge = 5'd10;
        7'd42: phase8_work_edge = 5'd10;
        7'd43: phase8_work_edge = 5'd10;
        7'd44: phase8_work_edge = 5'd11;
        7'd45: phase8_work_edge = 5'd11;
        7'd46: phase8_work_edge = 5'd11;
        7'd47: phase8_work_edge = 5'd11;
        7'd48: phase8_work_edge = 5'd12;
        7'd49: phase8_work_edge = 5'd12;
        7'd50: phase8_work_edge = 5'd12;
        7'd51: phase8_work_edge = 5'd12;
        7'd52: phase8_work_edge = 5'd13;
        7'd53: phase8_work_edge = 5'd13;
        7'd54: phase8_work_edge = 5'd13;
        7'd55: phase8_work_edge = 5'd13;
        7'd56: phase8_work_edge = 5'd14;
        7'd57: phase8_work_edge = 5'd14;
        7'd58: phase8_work_edge = 5'd14;
        7'd59: phase8_work_edge = 5'd14;
        7'd60: phase8_work_edge = 5'd15;
        7'd61: phase8_work_edge = 5'd15;
        7'd62: phase8_work_edge = 5'd16;
        7'd63: phase8_work_edge = 5'd15;
        7'd64: phase8_work_edge = 5'd16;
        7'd65: phase8_work_edge = 5'd15;
        7'd66: phase8_work_edge = 5'd16;
        7'd67: phase8_work_edge = 5'd17;
        7'd68: phase8_work_edge = 5'd16;
        7'd69: phase8_work_edge = 5'd17;
        7'd70: phase8_work_edge = 5'd18;
        7'd71: phase8_work_edge = 5'd17;
        7'd72: phase8_work_edge = 5'd18;
        7'd73: phase8_work_edge = 5'd17;
        7'd74: phase8_work_edge = 5'd18;
        7'd75: phase8_work_edge = 5'd18;
        default: begin end
      endcase
    end
  endfunction

  function automatic logic [6:0] phase8_work_column(input logic [6:0] work_id);
    begin
      phase8_work_column = 7'd0;
      case (work_id)
        7'd0: phase8_work_column = 7'd0;
        7'd1: phase8_work_column = 7'd0;
        7'd2: phase8_work_column = 7'd0;
        7'd3: phase8_work_column = 7'd0;
        7'd4: phase8_work_column = 7'd1;
        7'd5: phase8_work_column = 7'd1;
        7'd6: phase8_work_column = 7'd1;
        7'd7: phase8_work_column = 7'd2;
        7'd8: phase8_work_column = 7'd2;
        7'd9: phase8_work_column = 7'd2;
        7'd10: phase8_work_column = 7'd3;
        7'd11: phase8_work_column = 7'd3;
        7'd12: phase8_work_column = 7'd3;
        7'd13: phase8_work_column = 7'd4;
        7'd14: phase8_work_column = 7'd4;
        7'd15: phase8_work_column = 7'd4;
        7'd16: phase8_work_column = 7'd5;
        7'd17: phase8_work_column = 7'd5;
        7'd18: phase8_work_column = 7'd5;
        7'd19: phase8_work_column = 7'd6;
        7'd20: phase8_work_column = 7'd6;
        7'd21: phase8_work_column = 7'd6;
        7'd22: phase8_work_column = 7'd7;
        7'd23: phase8_work_column = 7'd7;
        7'd24: phase8_work_column = 7'd7;
        7'd25: phase8_work_column = 7'd8;
        7'd26: phase8_work_column = 7'd8;
        7'd27: phase8_work_column = 7'd8;
        7'd28: phase8_work_column = 7'd9;
        7'd29: phase8_work_column = 7'd9;
        7'd30: phase8_work_column = 7'd9;
        7'd31: phase8_work_column = 7'd10;
        7'd32: phase8_work_column = 7'd10;
        7'd33: phase8_work_column = 7'd10;
        7'd34: phase8_work_column = 7'd11;
        7'd35: phase8_work_column = 7'd11;
        7'd36: phase8_work_column = 7'd11;
        7'd37: phase8_work_column = 7'd12;
        7'd38: phase8_work_column = 7'd12;
        7'd39: phase8_work_column = 7'd12;
        7'd40: phase8_work_column = 7'd13;
        7'd41: phase8_work_column = 7'd13;
        7'd42: phase8_work_column = 7'd13;
        7'd43: phase8_work_column = 7'd14;
        7'd44: phase8_work_column = 7'd14;
        7'd45: phase8_work_column = 7'd14;
        7'd46: phase8_work_column = 7'd15;
        7'd47: phase8_work_column = 7'd15;
        7'd48: phase8_work_column = 7'd15;
        7'd49: phase8_work_column = 7'd16;
        7'd50: phase8_work_column = 7'd16;
        7'd51: phase8_work_column = 7'd16;
        7'd52: phase8_work_column = 7'd17;
        7'd53: phase8_work_column = 7'd17;
        7'd54: phase8_work_column = 7'd17;
        7'd55: phase8_work_column = 7'd18;
        7'd56: phase8_work_column = 7'd18;
        7'd57: phase8_work_column = 7'd18;
        7'd58: phase8_work_column = 7'd19;
        7'd59: phase8_work_column = 7'd19;
        7'd60: phase8_work_column = 7'd19;
        7'd61: phase8_work_column = 7'd20;
        7'd62: phase8_work_column = 7'd20;
        7'd63: phase8_work_column = 7'd20;
        7'd64: phase8_work_column = 7'd21;
        7'd65: phase8_work_column = 7'd21;
        7'd66: phase8_work_column = 7'd21;
        7'd67: phase8_work_column = 7'd22;
        7'd68: phase8_work_column = 7'd22;
        7'd69: phase8_work_column = 7'd22;
        7'd70: phase8_work_column = 7'd23;
        7'd71: phase8_work_column = 7'd23;
        7'd72: phase8_work_column = 7'd24;
        7'd73: phase8_work_column = 7'd24;
        7'd74: phase8_work_column = 7'd25;
        7'd75: phase8_work_column = 7'd25;
        default: begin end
      endcase
    end
  endfunction

  function automatic logic [8:0] phase8_work_shift(input logic [6:0] work_id);
    begin
      phase8_work_shift = 9'd0;
      case (work_id)
        7'd0: phase8_work_shift = 9'd307;
        7'd1: phase8_work_shift = 9'd76;
        7'd2: phase8_work_shift = 9'd205;
        7'd3: phase8_work_shift = 9'd276;
        7'd4: phase8_work_shift = 9'd19;
        7'd5: phase8_work_shift = 9'd250;
        7'd6: phase8_work_shift = 9'd87;
        7'd7: phase8_work_shift = 9'd50;
        7'd8: phase8_work_shift = 9'd76;
        7'd9: phase8_work_shift = 9'd328;
        7'd10: phase8_work_shift = 9'd369;
        7'd11: phase8_work_shift = 9'd73;
        7'd12: phase8_work_shift = 9'd0;
        7'd13: phase8_work_shift = 9'd288;
        7'd14: phase8_work_shift = 9'd332;
        7'd15: phase8_work_shift = 9'd275;
        7'd16: phase8_work_shift = 9'd181;
        7'd17: phase8_work_shift = 9'd144;
        7'd18: phase8_work_shift = 9'd256;
        7'd19: phase8_work_shift = 9'd216;
        7'd20: phase8_work_shift = 9'd161;
        7'd21: phase8_work_shift = 9'd199;
        7'd22: phase8_work_shift = 9'd331;
        7'd23: phase8_work_shift = 9'd267;
        7'd24: phase8_work_shift = 9'd153;
        7'd25: phase8_work_shift = 9'd331;
        7'd26: phase8_work_shift = 9'd160;
        7'd27: phase8_work_shift = 9'd56;
        7'd28: phase8_work_shift = 9'd317;
        7'd29: phase8_work_shift = 9'd178;
        7'd30: phase8_work_shift = 9'd63;
        7'd31: phase8_work_shift = 9'd288;
        7'd32: phase8_work_shift = 9'd129;
        7'd33: phase8_work_shift = 9'd132;
        7'd34: phase8_work_shift = 9'd109;
        7'd35: phase8_work_shift = 9'd295;
        7'd36: phase8_work_shift = 9'd305;
        7'd37: phase8_work_shift = 9'd17;
        7'd38: phase8_work_shift = 9'd342;
        7'd39: phase8_work_shift = 9'd231;
        7'd40: phase8_work_shift = 9'd357;
        7'd41: phase8_work_shift = 9'd200;
        7'd42: phase8_work_shift = 9'd341;
        7'd43: phase8_work_shift = 9'd217;
        7'd44: phase8_work_shift = 9'd88;
        7'd45: phase8_work_shift = 9'd212;
        7'd46: phase8_work_shift = 9'd215;
        7'd47: phase8_work_shift = 9'd99;
        7'd48: phase8_work_shift = 9'd53;
        7'd49: phase8_work_shift = 9'd106;
        7'd50: phase8_work_shift = 9'd354;
        7'd51: phase8_work_shift = 9'd304;
        7'd52: phase8_work_shift = 9'd114;
        7'd53: phase8_work_shift = 9'd131;
        7'd54: phase8_work_shift = 9'd300;
        7'd55: phase8_work_shift = 9'd242;
        7'd56: phase8_work_shift = 9'd240;
        7'd57: phase8_work_shift = 9'd271;
        7'd58: phase8_work_shift = 9'd180;
        7'd59: phase8_work_shift = 9'd331;
        7'd60: phase8_work_shift = 9'd205;
        7'd61: phase8_work_shift = 9'd330;
        7'd62: phase8_work_shift = 9'd13;
        7'd63: phase8_work_shift = 9'd39;
        7'd64: phase8_work_shift = 9'd346;
        7'd65: phase8_work_shift = 9'd112;
        7'd66: phase8_work_shift = 9'd357;
        7'd67: phase8_work_shift = 9'd1;
        7'd68: phase8_work_shift = 9'd0;
        7'd69: phase8_work_shift = 9'd1;
        7'd70: phase8_work_shift = 9'd0;
        7'd71: phase8_work_shift = 9'd0;
        7'd72: phase8_work_shift = 9'd0;
        7'd73: phase8_work_shift = 9'd0;
        7'd74: phase8_work_shift = 9'd0;
        7'd75: phase8_work_shift = 9'd0;
        default: begin end
      endcase
    end
  endfunction

  function automatic logic phase8_work_valid(input logic [6:0] work_id);
    begin
      phase8_work_valid = (work_id < 7'd76);
    end
  endfunction
endpackage

`endif
